### ISSUE TITLE
email reports to correct contact

### ISSUE THREAD

**Issue by stefpiatek** [UCL-ARC/rred-reports#12]
For now I think setup with local email and run tests with a fake smtp server? (I'm imagining where you pass an argument into the constructor, in production it'd be a a connected server, in test it'd be a fake SMTP server), or maybe we mock out part of the email sending so we just capture it

**Comment by harryjmoss** [comment]
Production side of this is less simple than I first thought - does the DSH have a SMTP server we can use/authenticate against? Alternatively do we use the ISD or CS server? Auth will be an issue too as noted above

**Comment by stefpiatek** [comment]
This part would be done outside of the DSH because the only way in or out is by using the data transfer directories. There is a project email account, will track down the password for it

**Comment by stefpiatek** [comment]
[exchangelib](https://ecederstrand.github.io/exchangelib/#creating-updating-deleting-sending-moving-archiving-marking-as-junk) looks like an easy-ish way to authenticate with the exchange mailserver and you can send from a delegated mailbox using the `account` option in the `Messages` constructor so I think that could work if you haven't already chosen a library.
