### ISSUE TITLE
sending of school reports using distribution list

### ISSUE THREAD

**Issue by stefpiatek** [UCL-ARC/rred-reports#34]
- [ ] convert docx to pdfs - maybe using https://github.com/AlJohri/docx2pdf?

```
from docx2pdf import convert

convert("input.docx")
convert("input.docx", "output.pdf")
convert("my_docx_folder/")
```

other suggestions: https://stackoverflow.com/questions/6011115/doc-to-pdf-using-python

- [ ] Would also like UAT run during report generation, where all PDFs are created and then combined into one long document, should be able to generate all of them, and then join them. This looks like it should work [pypdf](https://github.com/py-pdf/pypdf)

```python
from pypdf import PdfMerger

pdfs = ['file1.pdf', 'file2.pdf', 'file3.pdf', 'file4.pdf']

merger = PdfMerger()

for pdf in pdfs:
    merger.append(pdf)

merger.write("result.pdf")
merger.close()
```

[real dispatch list](https://liveuclac-my.sharepoint.com/:x:/r/personal/sejjpia_ucl_ac_uk/Documents/projects/rred/reports/inputs/Dispatch%20list%202021-22.xlsx?d=w21cd0c85b9b048f08df84758f65db9da&csf=1&web=1&e=93q53c)
[text to be included in email for 2021](https://liveuclac-my.sharepoint.com/:w:/r/personal/sejjpia_ucl_ac_uk/Documents/projects/rred/reports/inputs/Email%20to%20go%20out%20with%20school%20report%202021_22.docx?d=wa046a6d02fb240c88800427788b5305c&csf=1&web=1&e=d3IOJL)

- [x] Stef to add distribution list layout to the repo 
- [x] Stef to check all MIT-compatible licences 
- [ ] Read dispatch list using the school id, if there is no teacher email, use the teacher leader email. Multiple teachers can exist per school, so probably best to send the report to multiple recipients from the same school rather than sending multiple emails

**Comment by harryjmoss** [comment]
@stefpiatek Some questions around the dispatch list that I haven't fully formed yet
- Do we want to have the dispatch list manually downloaded to some directory in the repo
- Can the email content just go in the repo? Apart from the school ID in the subject and *maybe* the IOE email I can't see anything sensitive in there. Might just save as HTML to match the formatting in the doc
- Think we agreed report creation should include conversion to PDF and concatenation into a single file - do we want to keep email sending outside of this?

**Comment by stefpiatek** [comment]
1. Yeah dispatch list will be added, but not committed to repo
2. Happy with all email content to be added to repo, I'd allow for it to change for each year
3. Yeah I think emailing is a separate CLI command so we can inspect the reports and make sure everyone is happy with them
