### ISSUE TITLE
DSH share access and redcap access for harry and katie

### ISSUE THREAD

**Issue by stefpiatek** [UCL-ARC/rred-reports#4]

**Comment by stefpiatek** [comment]
Leaving it to @katiebuntic to follow up in the next week or two if she or @harryjmoss don't have access to DSH shares or redcap (depending on DSH induction, may have to wait for a follow up from harry's end)

**Comment by harryjmoss** [comment]
DSH induction completed!

**Comment by harryjmoss** [comment]
@harryjmoss to chase PI to check REDCap access

**Comment by katiebuntic** [comment]
@katiebuntic has access to REDCap and the shared folder now
