### ISSUE TITLE
using one school, ensure population of template with no filtering

### ISSUE THREAD

**Issue by stefpiatek** [UCL-ARC/rred-reports#5]
starting with some fake data that is very simple, maybe a couple of teachers with a couple of students with all data filled in. Worth reading [BI RRED tasks](https://liveuclac-my.sharepoint.com/:w:/r/personal/sejjpia_ucl_ac_uk/Documents/projects/rred/reports/BI%20RRED%20task%20explained%20R.docx?d=wa53e5c4e8ce64413bb9edfbd8c6e103a&csf=1&web=1&e=fhAEWm) for sections on how to populate data into this [school_template](https://liveuclac-my.sharepoint.com/:w:/r/personal/sejjpia_ucl_ac_uk/Documents/projects/rred/reports/templates/Reading%20Recovery%20School%20Report%20template%202021-22.docx?d=w721ed57133704e2c9f1f19826d7ba507&csf=1&web=1&e=LlGYcU)

for expansion, have a method called `filter` which just returns the same dataframe. Later on we'll ensure that the filtering rules are applied here.

Would be good to have an integration test that reads in the data, uses template to write a new file and then has test code that ensures the document has been written correctly. Happy to have a chat through about the best way to run these tests, something like a pytest tmpdir or tmpdir factory would be useful

**Comment by harryjmoss** [comment]
We think this ticket contains these sub-tickets:
- add template to repo
- verify our filling function with this template
- separate ticket for testing
