### ISSUE TITLE
2023-24 reporting

### ISSUE THREAD

**Issue by stefpiatek** [UCL-ARC/rred-reports#81]
| Planned Date | Action                                                                                             | Done and notes | Completed Date |
| ------------ | -------------------------------------------------------------------------------------------------- | -------------- | -------------- |
| 22nd April    | ARC sends over previous year's school template for the RRED team to update to the current year                                                              | ✅                |   22nd April
| 1st July    | RRED team sends over school template for current year                                                           |           ✅      |         1st July        |
| 1st - 5th July    | ARC checks access for 2023-24 RRED project                                                              |        ✅         |                |
| 22st July | Study closes                                                                |        ✅         |                |
| 29th July  | ARC receive dispatch list from RRED                                                                |           ✅        |       29th July       |
| 29th July  | ARC downloads 2022-23 and 2023-24 years from redcap                                                      |           ✅        |     26th July     |
| 30th July - 2nd August     | ARC run wide to long conversion (may need to use the alias file from the previous year), send masterfile and any issues files over to RRED                 |          ✅         |     30th July     |
| 5th - 9th August   | RRED team resolves any issues found with schools                                                   |         ✅        |                |
| 5th - 9th August  | ARC reruns redcap extract and then ask RRED team to check masterfile for any required manual edits |       ✅          |                |
| 12th - 15th August    | ARC resolves any issues in generating reports, email UAT combined report to RRED team              |    ✅             |     8th August         |
| 12th - 15th August  | Katie emails indvidual reports to their own email address to ensure setup is working    |     ✅            |                |
| 19th August    | email individual reports to [ilc.comms@ucl.ac.uk](mailto:ilc.comms@ucl.ac.uk)                      |        ✅         |                |
| 30th August     | RRED team tests the dispatch list for emails working    |      ✅           |                |
| 10th September  | reports signed off by RRED, email to schools                                                       |       ✅          |        10th Sept        |
| 10th September  | ARC to archive masterfile and dispatch list on R drive                                                    |          ✅       |        11th Sept        |

**Comment by katiebuntic** [comment]
Closing as all completed 🎉
